---
- name: Create group
  group:
    name: testgroup

- name: Create user testuser
  user:
    name: testuser
    group: testgroup
    uid: 1002
    shell: /bin/bash
    createhome: yes
    home: /home/testuser

- name: Generate SSH key
  openssh_keypair:
    path: /home/testuser/.ssh/id_rsa
    type: rsa
    size: 2048
    force: yes

- name: Add SSH key to authorized_keys
  authorized_key:
    user: testuser
    state: present
    key: "{{ lookup('file', '/home/radmin/.ssh/id_rsa.pub') }}"

- name: Grant sudo privileges to testuser
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^testuser'
    line: 'testuser ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
